"""Shared schemas with compatibility-preserving lazy exports.

Importing one lightweight schema must not load the complete schema graph or
optional native biology dependencies. Existing ``from schemas import Name``
callers remain supported through module-level lazy attribute resolution.
"""

from __future__ import annotations

from utils.lazy_exports import install_lazy_exports


_EXPORTS = {
    "BiologicalPart": "schemas.design_ir",
    "DesignIR": "schemas.design_ir",
    "DesignRevision": "schemas.design_ir",
    "GeneticConstruct": "schemas.design_ir",
    "PartAssignment": "schemas.design_ir",
    "ProvenanceRecord": "schemas.design_ir",
    "RegulatoryInteraction": "schemas.design_ir",
    "topology_to_design_ir": "schemas.design_ir",
    "DesignDiff": "schemas.design_diff",
    "MetricChange": "schemas.design_diff",
    "PartChange": "schemas.design_diff",
    "compare_designs": "schemas.design_diff",
    "ReplacementResult": "schemas.design_operations",
    "ReplacementValidation": "schemas.design_operations",
    "replace_part_immutable": "schemas.design_operations",
    "validate_replacement": "schemas.design_operations",
    "DraftInteraction": "schemas.import_draft",
    "DraftPart": "schemas.import_draft",
    "FieldEvidence": "schemas.import_draft",
    "ImportDraft": "schemas.import_draft",
    "ImportValidation": "schemas.import_draft",
    "import_draft_from_json": "schemas.import_draft",
    "import_draft_to_design_ir": "schemas.import_draft",
    "validate_import_draft": "schemas.import_draft",
    "DESIGN_IR_V2_SCHEMA_VERSION": "schemas.design_ir_v2",
    "AttributedValue": "schemas.design_ir_v2",
    "BiologicalContext": "schemas.design_ir_v2",
    "BiologicalPartV2": "schemas.design_ir_v2",
    "ConstructPart": "schemas.design_ir_v2",
    "ConstructV2": "schemas.design_ir_v2",
    "DesignAssumption": "schemas.design_ir_v2",
    "DesignIRV2": "schemas.design_ir_v2",
    "DesignSpecification": "schemas.design_ir_v2",
    "FieldProvenance": "schemas.design_ir_v2",
    "PlasmidV2": "schemas.design_ir_v2",
    "design_ir_v2_from_dict": "schemas.design_ir_v2",
    "MigrationResult": "schemas.design_migrations",
    "design_ir_v2_to_v1_payload": "schemas.design_migrations",
    "migrate_design_ir_v1_to_v2": "schemas.design_migrations",
    "migrate_design_payload_to_v2": "schemas.design_migrations",
    "RunManifest": "schemas.run_manifest",
    "HostProfile": "schemas.host_profile",
    "default_ecoli_profile": "schemas.host_profile",
    "default_yeast_profile": "schemas.host_profile",
    "default_mammalian_profile": "schemas.host_profile",
    "host_profile_from_dict": "schemas.host_profile",
    "apply_host_profile_to_topology": "schemas.host_profile",
    "ExperimentalMeasurement": "schemas.host_optimization",
    "HostCalibrationResult": "schemas.host_optimization",
    "HostOptimizationCandidate": "schemas.host_optimization",
    "HostOptimizationResult": "schemas.host_optimization",
    "DesignSequenceAnalysis": "schemas.sequence_analysis",
    "SequenceAnalysisResult": "schemas.sequence_analysis",
    "SequenceIssue": "schemas.sequence_analysis",
    "SequenceChange": "schemas.sequence_optimization",
    "SequenceOptimizationRequest": "schemas.sequence_optimization",
    "SequenceOptimizationResult": "schemas.sequence_optimization",
    "PhaseWindow": "schemas.temporal_evaluation",
    "ToggleProfile": "schemas.temporal_evaluation",
    "OscillatorProfile": "schemas.temporal_evaluation",
    "TemporalEvaluatorConfig": "schemas.temporal_evaluation",
    "CONFIG_V1_0": "schemas.temporal_evaluation",
    "CONFIG_V1_1": "schemas.temporal_evaluation",
    "DEFAULT_TEMPORAL_CONFIG": "schemas.temporal_evaluation",
    "TEMPORAL_EVALUATOR_CONFIGS": "schemas.temporal_evaluation",
    "get_temporal_evaluator_config": "schemas.temporal_evaluation",
    "Notification": "schemas.notification",
    "EVIDENCE_BOM_SCHEMA_VERSION": "schemas.evidence_governance",
    "ClaimDecision": "schemas.evidence_governance",
    "ClaimEvidenceLink": "schemas.evidence_governance",
    "EvidenceRecord": "schemas.evidence_governance",
    "LicenseDecision": "schemas.evidence_governance",
    "build_evidence_manifest": "schemas.evidence_governance",
    "evaluate_claim": "schemas.evidence_governance",
    "evaluate_license_decision": "schemas.evidence_governance",
    "validate_evidence_manifest": "schemas.evidence_governance",
    "verify_evidence_manifest": "schemas.evidence_governance",
}

__all__ = list(_EXPORTS)
__getattr__, __dir__ = install_lazy_exports(globals(), _EXPORTS)
